services:
  api:
    container_name: nestjs_api
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo_db
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - nest-todo
    
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todo_db
    networks:
      - nest-todo

networks:
  nest-todo:
    driver: bridge

volumes:
  mongodb_data: 